apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: llama-2-7b-chat
  namespace: flux-system
  labels:
    artifact-kind: language-model
  annotations:
    ai.contrib.fluxcd.io/original-model-repo: https://huggingface.co/meta-llama/Llama-2-7b-chat-hf
    ai.contrib.fluxcd.io/model-repo: TheBloke/Llama-2-7B-Chat-GGUF
    ai.contrib.fluxcd.io/model-file: llama-2-7b-chat.Q5_K_M.gguf
    ai.contrib.fluxcd.io/model-version: 1.0.0
    ai.contrib.fluxcd.io/format: GGUFv2
    ai.contrib.fluxcd.io/family: llama # backend
    ai.contrib.fluxcd.io/context-size: 4096
    ai.contrib.fluxcd.io/quantization: Q5_K_M
    ai.contrib.fluxcd.io/size-on-disk: 4.7G
    ai.contrib.fluxcd.io/memory-required: 7.28G
    ai.contrib.fluxcd.io/layers: 15 # which can be offloaded to GPU
    ai.contrib.fluxcd.io/prompt-template: |-
      [INST] <<SYS>>
      You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe.  Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature. If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.
      <</SYS>>
      {prompt}[/INST]
spec:
  interval: 10m
  url: oci://ghcr.io/llm-gitops/models/llama-2-7b-chat-4k
  ref:
    tag: v1.0.0-q5km-gguf
  layerSelector:
    mediaType: "application/vnd.cncf.flux.content.v1.tar+gzip"
    operation: copy
