name: build-and-push

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        default: 'main'
      model_file:
        required: true
      model_repo:
        required: true
      model_image:
        required: true

permissions:
  packages: write # needed for ghcr.io access

jobs:
  build:
    name: "build ${{ github.event.inputs.model_image }}"
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
    # Checkout your repo
    - name: Checkout code
      uses: actions/checkout@v2

    # Install Python 3.10
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    # Install Flux v2 CLI
    - name: Setup Flux CLI
      uses: fluxcd/flux2/action@main

    # Install huggingface_hub package
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install huggingface_hub

    - name: Download model
      env:
        MODEL_REPO: ${{ github.event.inputs.model_repo }}
        MODEL_FILE: ${{ github.event.inputs.model_file }}
        MODEL_IMAGE: ${{ github.event.inputs.model_image }}
      run: |
        python download.py

        cd .model
        rm .keep # delete the place holder file
        
        MODEL_DIR=$PWD
        pushd .
        tree .
        TARGET=$(readlink $MODEL_FILE)
        cd $(dirname $MODEL_FILE)
        cp --remove-destination $TARGET $(basename $MODEL_FILE)
        popd
        rm -rf $TARGET
        
        # flatten structure
        find . -mindepth 2 -type f | while read -r file; do
            # Move each file to the /.models directory
            mv "$file" "${MODEL_DIR}/$(basename "$file")"
        done
        # once all files have been moved, find and remove any empty directories
        find . -type d -empty -delete

    - name: Push model
      env:
        MODEL_REPO: ${{ github.event.inputs.model_repo }}
        MODEL_FILE: ${{ github.event.inputs.model_file }}
        MODEL_IMAGE: ${{ github.event.inputs.model_image }}
      run: |
        cd .model
        tree .
        flux push artifact \
          --creds chanwit:${{ secrets.GHCR_TOKEN }} \
          oci://ghcr.io/llm-gitops/models/${MODEL_IMAGE} \
          --timeout 120m0s \
          --path="./" \
          --source="$(git config --get remote.origin.url)" \
          --revision="$(git branch --show-current)@sha1:$(git rev-parse HEAD)"
