name: llama-2-7b-chat

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - '.github/workflows/llama-2-7b-chat.yaml'
      - 'llama-2-7b-chat/**'

permissions:
  packages: write # needed for ghcr.io access

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
      run: |
        curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -u chanwit:${{ secrets.GHCR_TOKEN }} \
            https://api.github.com/repos/llm-gitops/models/actions/workflows/build-and-push.yaml/dispatches \
            -d '{
                    "ref":"main",
                    "inputs": {
                      "branch": "main",
                      "model_repo": "TheBloke/Llama-2-7B-Chat-GGUF",
                      "model_file": "llama-2-7b-chat.Q5_K_M.gguf",
                      "model_image": "llama-2-7b-chat-4k:v1.0.0-q5km-gguf"
                    }
                }'
